### ISSUE TITLE
What platform to run this code on?

### ISSUE THREAD

**Issue by sakhnik** [alexcode9/edecoa-mqtt#1]
Hi, thanks for sharing the code. On what board do you run this code?
When I tried a WiFi dongle from PowMr, it was rebooted by the inverter every 10 seconds.

**Comment by alexcode9** [comment]
hey @sakhnik this code was meant to be run on ESP8266 hardware, but it was a work in progress and was abandoned in a NOT WORKING state. I'm planning to restore it the future to be run on ESP32.

**Comment by sakhnik** [comment]
Thanks! Does the communication happen over RS-232 or RS-485?
Did you do reverse engineering to figure out the modbus registers? Or is there any documentation available?

Github search for `edecoa` gives two results: https://github.com/search?q=edecoa&type=repositories . The other one in Python sends the command QPIGS to get status information. Does the inverter support both protocols? Or it's the matter of inverter model?

**Comment by alexcode9** [comment]
My plan was to reverse engineer it attaching a digital analyzer to the little command panel board which uses an rj45
![image](https://github.com/user-attachments/assets/7f2a83fa-b727-4c10-84f6-2ec7c63a0fe3)

**Comment by alexcode9** [comment]
I was specifically working on pure sine waves inverters like these https://www.edecoa.com/collections/pure-sine-wave

**Comment by sakhnik** [comment]
Ok, got it, thanks!
